version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
