INSERT INTO sector (id, name) 
VALUES 
(1, 'Energy')
,(2, 'Materials')
,(3, 'Capital Goods')
,(4, 'Commercial & Professional Services')
,(5, 'Transportation')
,(6, 'Automobiles & Components')
,(7, 'Consumer Durables & Apparel')
,(8, 'Consumer Services')
,(9, 'Retailing')
,(10, 'Food & Staples Retailing')
,(11, '"Food, Beverage & Tobacco"')
,(12, 'Household & Personal Products')
,(13, 'Health Care Equipment & Services')
,(14, 'Banks')
,(15, 'Diversified Financials')
,(16, 'Insurance')
,(17, 'Software & Services')
,(18, 'Telecommunication Services')
,(19, 'Utilities')
,(20, 'Real Estate Management&Development')